spring:
  application:
    name: QuestLoggers

  datasource:
    url: ${DB_URL}?rewriteBatchedStatements=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update

server:
  error:
    include-message: always

jwt:
  secret:
    key: rP1K0aKHr+KQIvAy3CvjGPAnvz1bzA2heM0H98D9lMA=